### ISSUE TITLE
Make HeaderValue properties public

### ISSUE THREAD

**Issue by jonfriesen** [mathetake/envoy-dynamic-modules#27]
Hi @mathetake 

Would it be possible to make the properties of [HeaderValue](https://github.com/mathetake/envoy-dynamic-modules/blob/main/sdks/go/envoy/envoy.go#L76) public?

I'm implementing a Go host side of the [ABI spec](https://github.com/mathetake/envoy-dynamic-modules/blob/main/sdks/go/envoy/abi_nocgo.go) and this is blocking me from implementing the `RequestHeaders` and `ResponseHeaders` interfaces.

I realize that you're still early on this and it might change. We're willing to adapt, this is just a blocker right now.

Thanks!

**Comment by mathetake** [comment]
I guessed this is essentially what you wanted https://github.com/mathetake/envoy-dynamic-modules/commit/b2cd707ee827c92a4f41aea519e1904070164bbd does this work for you now?

**Comment by jonfriesen** [comment]
That's perfect! Thanks for the insanely quick turn around. Have an awseome weekend! 🎉

**Comment by mathetake** [comment]
you too! 💯
